---
title: "Lab 05 - La Quinta is Spanish for next to Denny's, Pt. 2"
author: "Cailey Fay"
date: "10.14.25"
output: github_document
---

### Load packages and data

```{r load-packages, message = FALSE}
library(tidyverse) 
library(dsbox) 
```

```{r load-data, message = FALSE}
states <- read_csv("data/states.csv")
```

### Exercise 1

```{r exercise1}
dn_ak <- dennys %>%
  filter(state == "AK")
nrow(dn_ak)

lq_ak <- laquinta %>%
  filter(state == "AK")

nrow(lq_ak)

#there are 3 dennys and 2 laquintas in alaska.
```

### Exercise 2

```{r exercise2}
#6 pairings- how tf do you code this though?

```
### Exercise 3 and 4
``` {r exercise3 and 4}
dn_lq_ak <- full_join(dn_ak, lq_ak,
  by = "state"
)
dn_lq_ak

#there are 6 observations. Each row has the x (alaska dennys) location info and the y (alaska laquinta) location. 

```

### Exercise 5
``` {r exercise 5}
#we use the mutate function 
haversine <- function(long1, lat1, long2, lat2, round = 3) {
  # convert to radians
  long1 <- long1 * pi / 180
  lat1 <- lat1 * pi / 180
  long2 <- long2 * pi / 180
  lat2 <- lat2 * pi / 180

  R <- 6371 # Earth mean radius in km

  a <- sin((lat2 - lat1) / 2)^2 + cos(lat1) * cos(lat2) * sin((long2 - long1) / 2)^2
  d <- R * 2 * asin(sqrt(a))

  return(round(d, round)) # distance in km
}
```
...

### Exercise 6
```{r exercise6}
dn_lq_ak <- dn_lq_ak %>%
  mutate(distance = haversine(longitude.x,latitude.x,longitude.y,latitude.y))

```

...
### Exercise 7
```{r exercise7}
dn_lq_ak_mindist <- dn_lq_ak %>%
  group_by(address.x) %>%
  summarize(closest = min(distance))
```

### Exercise 8

```{r exercise8}
#every dennys has a laquinta within six miles 
#from lab 4
dn <- dennys %>%
  mutate(establishment = "Denny's")
lq <- laquinta %>%
  mutate(establishment = "La Quinta")
dn_lq <- bind_rows(dn, lq)
# made the new combined variable successfully 
ggplot(dn_lq, mapping = aes(
  x = longitude,
  y = latitude,
  color = establishment
)) +
  geom_point()

AKonly <- dn_lq %>%
  filter(state == "AK")
ggplot(AKonly, mapping = aes(
  x = longitude,
  y = latitude,
  color = establishment
)) +
  geom_point()
#you can see that the dennys and laqintas are clustered together.
#and from number 7 the greatest minimum distance between a laquinta and dennys was just under 6 miles, and the least minimum distance was around 2 miles. 
```
### Exercise 9
```{r exercise9}
dn_nc <- dennys %>%
  filter(state == "NC")

lq_nc <- laquinta %>%
  filter(state == "NC")

dn_lq_nc <- full_join(dn_nc, lq_nc,
  by = "state"
)
dn_lq_ak
#this built the pairings for NC dennys and laquinta locations
#below I am going to mutate so that we have distance

dn_lq_nc <- dn_lq_nc %>%
  mutate(distance = haversine(longitude.x,latitude.x,longitude.y,latitude.y))

#finally I'm going to get the minimum distance

dn_lq_nc_mindist <- dn_lq_nc %>%
  group_by(address.x) %>%
  summarize(closest = min(distance))

#not sure how to visualize this 
the closets dennys to a laquinta ranged from around a mile to 187 miles. Much more spread out / not clustered together compared to alaska. 

```
